language: node_js

os: osx

node_js:
- 8

script:
- yarn
- yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_KEY  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: dist
    on:
      branch: master

cache:
  yarn: true
  directories:
    - node_modules
