service: js13kGames-bot

package:
  exclude:
    - ./src/**
    - ./doc/**
    - ./.jest-cache/**

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 180
  logRetentionInDays: 14
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::js13kgames-entry-preview"
  environment:
    AWS_BUCKET_NAME: js13kgames-entry-preview

functions:
  cron:
    handler: build/handle-cron.handle
    events:
      - schedule: rate(5 minutes)
