service: js13kGames-bot

package:
  exclude:
    - ./src/**
    - ./doc/**
    - ./.jest-cache/**
    - ./node_modules/.cache/**
    - README.md
    - license

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 280
  region: eu-west-1
  logRetentionInDays: 14
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"
  environment:
    AWS_BUCKET_NAME: js13kgames-entry-preview

functions:
  cron:
    handler: build/handle-cron.handle
    events:
      - schedule: rate(5 minutes)
