service: js13kGames-bot

package:
  exclude:
    - ./src/**
    - ./doc/**
    - ./.jest-cache/**
    - ./node_modules/.cache/**
    - README.md
    - license

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 120
  region: eu-west-1
  stage: stage
  logRetentionInDays: 14
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  environment:
    AWS_BUCKET_NAME: js13kgames-entry-preview
    GITHUB_WEBHOOK_URL:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "ApiGatewayRestApi"
          - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"

functions:
  github-webhook:
    handler: build/handle-github-webhook.handle
    events:
      - http: POST webhook

  detect-new-release:
    handler: build/handle-cron.handle
    events:
      - schedule: rate(2 minutes)
